[phases.setup]
nixPkgs = ['python39', 'python39Packages.pip', 'python39Packages.virtualenv']

[phases.install]
cmds = [
  'cd backend',
  'python -m venv venv',
  'source venv/bin/activate',
  'pip install -r requirements.txt'
]

[phases.build]
cmds = ['echo "Build phase completed"']

[start]
cmd = 'cd backend && source venv/bin/activate && python app.py'