[phases.setup]
nixPkgs = ['python39', 'pip']

[phases.install]
cmds = [
  'cd backend',
  'pip install -r requirements.txt'
]

[phases.build]
cmds = ['echo "Build phase completed"']

[start]
cmd = 'cd backend && python app.py'